name: Production

on:
  pull_request:
    types: ["opened", "edited", "synchronize", "closed"]
    branches: ["main"]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT }}

    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node dependencies
        run: yarn install
      - name: Build
        run: yarn build
    outputs:
      status: ${{ job.status }}

  deploy:
    name: Deploy to Netlify
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
    outputs:
      status: ${{ job.status }}